[build]
  command = "pnpm build"
  publish  = "dist"

[[redirects]]
  from = "/functions/*"
  to = "https://gpcxxatgsxisukznygkc.functions.supabase.co/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
